import Footer from "@/layout/Footer";
import "./globals.css";
import Layout from "@/layout/Layout";
import NextAuthProvider from "@/providers/NextAuthProvider";
import Header from "@/layout/Header";

export const metadata = {
  title: "املاک",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className=" mx-auto  overflow-x-hidden font-vazir ">
        <NextAuthProvider>
          <Header/>
        {children}
        <Footer/>
        </NextAuthProvider>
      </body>
    </html>
  );
}
