import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import connectDB from "@/utils/connectDB";
import User from "@/models/user";
import DashboardSidebar from "@/layout/DashboardSidebar";

export const metadata = {
  title: "پنل کاربری پروژه املاک",
  description: "Generated by create next app",
};

export default async function DashboardLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) return redirect("/signin");

  await connectDB();
  const user = await User.findOne({ email: session.user.email });
  if (!user) return <h3>مشکلی پیش آمده</h3>;
  return (
    <DashboardSidebar email={user.email} role={user.role}>
      {children}
    </DashboardSidebar>
  );
}
